google.maps.__gjsload__('stats', function(_){var nFa=function(a,b){return new _.WC(a,b)},oFa=function(a){_.F(this,a,2)},pFa=function(a){_.F(this,a,6)},qFa=function(a,b,c,d){var e={};e.host=document.location&&document.location.host||window.location.host;e.v=a.split(".")[1]||a;e.fv=a;e.r=Math.round(1/b);c&&(e.client=c);d&&(e.key=d);return e},sFa=function(a){var b=document;this.token=rFa;this.i=a+"/maps/gen_204";this.h=b},gJ=function(a,b,c){var d=[];_.Ik(a,function(e,f){d.push(f+b+e)});return d.join(c)},tFa=function(a){var b={};_.Ik(a,function(c,
d){b[encodeURIComponent(d)]=encodeURIComponent(c).replace(/%7C/g,"|")});return gJ(b,":",",")},uFa=function(a){if(a instanceof hJ||a instanceof iJ||a instanceof jJ)return a;if("function"==typeof a.next)return new hJ(function(){return a});if("function"==typeof a[_.u(_.x.Symbol,"iterator")])return new hJ(function(){return a[_.u(_.x.Symbol,"iterator")]()});if("function"==typeof a.vj)return new hJ(function(){return a.vj()});throw Error("Not an iterator or iterable.");},hJ=function(a){this.g=a},iJ=function(a){this.g=
a},jJ=function(a){hJ.call(this,function(){return a});this.i=a},kJ=function(a,b){this.h={};this.g=[];this.i=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof kJ)for(c=a.kh(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])},vFa=function(a,b){return a===b},mJ=function(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];lJ(a.h,
d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],lJ(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}},lJ=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},wFa=function(a,b,c,d){var e=_.Gd(_.Kf,0,1);this.l=a;this.o=b;this.j=e;this.h=c;this.i=d;this.g=new kJ;this.m=Date.now()},nJ=function(a,b,c,d,e){this.m=a;this.o=b;this.l=c;this.i=d;this.j=e;this.h={};this.g=[]},xFa=function(a,b,c){var d=_.uea;this.i=a;_.K.bind(this.i,"set_at",this,this.j);
_.K.bind(this.i,"insert_at",this,this.j);this.l=b;this.o=d;this.m=c;this.h=0;this.g={};this.j()},oJ=function(){this.g=_.G(_.Kf,6);this.i=_.G(_.Kf,16);if(_.pi[35]){var a=_.Pd(_.Kf);a=_.G(a,11)}else a=_.ks;this.h=new sFa(a);(a=_.Ij)&&new xFa(a,(0,_.Oa)(this.h.g,this.h),!!this.g);this.o=_.G(_.Qd(_.Kf),1);this.C={};this.l={};this.m=_.Gd(_.Kf,0,1);a=this.j=new pFa;var b=_.G(_.Qd(_.Kf),1);a.H[1]=b;this.g&&(this.j.H[2]=this.g);this.i&&(this.j.H[3]=this.i)};_.D(oFa,_.E);var pJ;_.D(pFa,_.E);var rFa=Math.round(1E15*Math.random()).toString(36);sFa.prototype.g=function(a,b){b=b||{};var c=Date.now().toString(36);b.src="apiv3";b.token=this.token;b.ts=c.substr(c.length-6);a.cad=tFa(b);a=gJ(a,"=","&");a=this.i+"?target=api&"+a;_.Se(new _.Re(this.h),"IMG").src=a;(b=_.C.__gm_captureCSI)&&b(a)};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
hJ.prototype.vj=function(){return new iJ(this.g())};hJ.prototype[_.u(_.x.Symbol,"iterator")]=function(){return new jJ(this.g())};hJ.prototype.h=function(){return new jJ(this.g())};_.B(iJ,_.Qi);iJ.prototype.next=function(){return this.g.next()};iJ.prototype[_.u(_.x.Symbol,"iterator")]=function(){return new jJ(this.g)};iJ.prototype.h=function(){return new jJ(this.g)};_.B(jJ,hJ);jJ.prototype.next=function(){return this.i.next()};_.n=kJ.prototype;_.n.qe=function(){mJ(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};_.n.kh=function(){mJ(this);return this.g.concat()};_.n.has=function(a){return lJ(this.h,a)};_.n.equals=function(a,b){if(this===a)return!0;if(this.size!=a.size)return!1;b=b||vFa;mJ(this);for(var c,d=0;c=this.g[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};_.n.isEmpty=function(){return 0==this.size};_.n.clear=function(){this.h={};this.i=this.size=this.g.length=0};_.n.remove=function(a){return this.delete(a)};
_.n.delete=function(a){return lJ(this.h,a)?(delete this.h[a],--this.size,this.i++,this.g.length>2*this.size&&mJ(this),!0):!1};_.n.get=function(a,b){return lJ(this.h,a)?this.h[a]:b};_.n.set=function(a,b){lJ(this.h,a)||(this.size+=1,this.g.push(a),this.i++);this.h[a]=b};_.n.forEach=function(a,b){for(var c=this.kh(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.n.clone=function(){return new kJ(this)};_.n.keys=function(){return uFa(this.vj(!0)).h()};_.n.values=function(){return uFa(this.vj(!1)).h()};
_.n.entries=function(){var a=this;return nFa(_.u(this,"keys").call(this),function(b){return[b,a.get(b)]})};_.n.vj=function(a){mJ(this);var b=0,c=this.i,d=this,e=new _.Qi;e.next=function(){if(c!=d.i)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)return _.qk;var f=d.g[b++];return{value:a?f:d.h[f],done:!1}};return e};wFa.prototype.C=function(a){var b=this;0===this.g.size&&window.setTimeout(function(){var d=qFa(b.o,b.j,b.h,b.i);d.t=Date.now()-b.m;for(var e=b.g,f={},g=_.A(_.u(e,"keys").call(e)),h=g.next();!h.done;h=g.next())h=h.value,f[h]=e.get(h);_.ib(d,f);b.g.clear();b.l.g({ev:"api_maprft"},d)},500);var c=this.g.get(a,0)+1;this.g.set(a,c)};nJ.prototype.C=function(a){this.h[a]||(this.h[a]=!0,this.g.push(a),2>this.g.length&&_.ku(this,this.F,500))};nJ.prototype.F=function(){for(var a=qFa(this.o,this.l,this.i,this.j),b=0,c;c=this.g[b];++b)a[c]="1";a.hybrid=+_.Dm();this.g.length=0;this.m.g({ev:"api_mapft"},a)};xFa.prototype.j=function(){for(var a;a=this.i.removeAt(0);){var b=a.mz;a=a.timestamp-this.o;++this.h;this.g[b]||(this.g[b]=0);++this.g[b];if(20<=this.h&&!(this.h%5)){var c={s:b};c.sr=this.g[b];c.tr=this.h;c.te=a;c.hc=this.m?"1":"0";this.l({ev:"api_services"},c)}}};oJ.prototype.G=function(a){a=_.ef(a);var b=this.C[a];b||(b=new nJ(this.h,this.o,this.m,this.g,this.i),this.C[a]=b);return b};oJ.prototype.F=function(a){a=_.ef(a);this.l[a]||(this.l[a]=new wFa(this.h,this.o,this.g,this.i));return this.l[a]};
oJ.prototype.J=function(a){if(_.Rf){var b=this.j.clone(),c=Math.floor(Date.now()/1E3);b.H[0]=c;c=new oFa(_.J(b,5));c.H[0]=Math.round(1/this.m);c.H[1]=a;a=this.h;c={ev:"api_map_style"};var d=new _.fh;pJ||(pJ={M:"issssm",Z:["is"]});var e=pJ;b=d.ib(b.Mb(),e);c.pb=encodeURIComponent(b).replace(/%20/g,"+");b=gJ(c,"=","&");_.Se(new _.Re(a.h),"IMG").src=a.i+"?target=api&"+b}};_.Xe("stats",new oJ);});
