/*Copyright (c) 2011, 2022, Oracle and/or its affiliates.  All rights reserved.*/
/*MF:S MF:L*/
try{(function(q,k){function y(a,g,k){return a?a&&a.src&&a.src.indexOf&&(-1!==a.src.indexOf("mansuetodfp4895838934/"+g)||-1!==a.src.indexOf("mansuetodfp4895838934%2F"+g))?"undefined"!==typeof a[k]&&!0===a[k]?!1:a[k]=!0:!1:!1}function C(a,g){return!g(a.parent)&&!g(a.top)}function D(){var a=!1;try{a=!!window.top.frames[t.pcode+"_MOAT_IFRAME"]}catch(g){}return a}function z(){if(!a.e.e()){a.e.f(!0);var e=w,g="scriptfound"+t.pcode,d=k.floor(k.random()*k.pow(10,10)),n=k.floor(k.random()*k.pow(10,12)),v=
e.className||"-",b=e.getAttribute("src");b||(b="z.moatads.com/mansuetodfp4895838934/moatad.js#");e={sli:"MANSUETODFPCW3"};"string"===typeof t.altKey&&(e[t.altKey]=1);"object"===typeof t.dSA&&(e.dSA=JSON.stringify(t.dSA));e.useSlotIkey=t.useSlotIkey;var c;0>b.indexOf("#")&&0>b.indexOf("?")?c="#":(c=b[b.length-1],c="&"!==c&&"#"!==c?"&":"");var A=[];for(key in e)e.hasOwnProperty(key)&&A.push(key+"="+e[key]);c+=A.join("&");b+=c;v=encodeURIComponent(v)+"@@@"+encodeURIComponent(b);v+="@@@"+encodeURIComponent(JSON.stringify({}));
window.top.postMessage("MSFAPI#1.2#"+n+"#"+g+"#"+d+"#"+v,"*")}}var a={},t={pcode:"mansuetoprebidheader15141606144"};(function(){function e(a){var c=a||{},e=0,l=!1,f="MFPA_"+k.floor(k.random()*k.pow(10,12)),h=.1>k.random();this.__d=function(a){if(h&&a&&"object"===typeof a)for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};this.sp=function(a){if(!h||!a||l&&a.LOAD)return!1;a.LOAD?(e=c.e=0,l=!0):a.FALLBACK_LOADED?(c.tc=1,c.e=9,e=1):a.AD_FOUND&&(c.tc=1,c.id=1,c.e=9,e=2);c.g=e;c.cm=10;var b;a="";for(b in c)if(c.hasOwnProperty(b)){var m=
encodeURIComponent(c[b]);a+="&"+b+"="+m}b=a.slice(1);a=b;m=new q;m=[m.getFullYear(),("0"+(m.getMonth()+1)).slice(-2),("0"+m.getDate()).slice(-2)].join("-");a+="MOAT_FEATHER_DEBUG1"+m;var r=0;if(0==a.length)a=r;else{for(m=0;m<a.length;m++)var f=a.charCodeAt(m),r=(r<<5)-r+f,r=r&r;a=k.abs(r)}b="https://px.moatads.com/pixel.gif?"+b+"&na="+a+"&cs=0";var p;try{"undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf)?omidNative.sendUrl(b):(p=new Image(1,1),p.src=b)}catch(g){p=
new Image(1,1),p.src=b}return!0};this.an=function(){return f};this.FPAA=function(){return h}}function g(b){if(null==b||a.c.c(b))return!1;var c=b.length;return 1===b.nodeType&&c?!0:"string"===typeof b||a.c.d(b)||0===c||"number"===typeof c&&0<c&&c-1 in b}function d(a,c,e,l){var f,h=typeof a;if(a)if("function"===h)for(f in a){if("prototype"!=f&&"length"!=f&&"name"!=f&&(l||!a.hasOwnProperty||a.hasOwnProperty(f))&&(h=c.call(e,a[f],f),"boolean"===typeof h&&!h))break}else if("number"===h)for(f=0;f<a&&(h=
c.call(e,a,f),"boolean"!==typeof h||h);f++);else if("function"===typeof a.every)a.every(function(a,b,m){a=c.call(e,a,b);return!("boolean"===typeof a&&!a)});else if(g(a))for(f=0;f<a.length&&(h=c.call(e,a[f],f),"boolean"!==typeof h||h);f++);else for(f in a)if(l||a.hasOwnProperty(f))if(h=c.call(e,a[f],f),"boolean"===typeof h&&!h)break;return a}var n,v={};a.c=a.c||{};a.c.e=function(b){return function(){var c;c=!1;return function(e){try{return b&&b.apply?b.apply(null,arguments):b(e)}catch(g){if(!c){c=
!0;var l=(new q).getTime();this.MoatETS||(this.MoatETS=l);this.MoatEMC||(this.MoatEMC=0);var f=36E5<=l-this.MoatETS,h="";try{h=b.toString()}catch(k){h="failed"}h=g.name+" in closure (cb): "+g.message+", stack="+g.stack+", \ncb="+h+"\n";if(!f&&10>this.MoatEMC){this["Moat#EMC"]++;try{var d="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf),u=d?"":document.referrer,m="undefined"===typeof AD_VIEW_HASH?"MANSUETODFPCW3":AD_VIEW_HASH,r="undefined"!==typeof a&&a.a&&
a.a.a?a.a.a:"",x="https://px.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(m)+"&k="+escape(h)+"&ar="+escape("e27dbc83ae5-clean")+"&iw="+escape("1347236")+"&bq="+escape(r)+"&j="+escape(u)+"&cs="+(new q).getTime();if(d)omidNative.sendUrl(x);else{var p=new Image(1,1);p.src=x}}catch(k){}}else if(f){this.MoatEMC=1;this["Moat#ETS"]=l;try{u=(d="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf))?"":document.referrer,m="undefined"===typeof AD_VIEW_HASH?
"MANSUETODFPCW3":AD_VIEW_HASH,r="undefined"!==typeof a&&a.a&&a.a.a?a.a.a:"",x="https://px.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(m)+"&k="+escape(h)+"&ar="+escape("e27dbc83ae5-clean")+"&iw="+escape("1347236")+"&bq="+escape(r)+"&j="+escape(u)+"&cs="+(new q).getTime(),d?omidNative.sendUrl(x):(p=new Image(1,1),p.src=x)}catch(k){}}}}}}()};a.c.f=function(){if(!n){n=new e;var b={e:0};b.d=a.b.a.moatClientLevel1+":"+a.b.a.moatClientLevel2+":"+a.b.a.moatClientLevel3+":"+a.b.a.moatClientLevel4;
b.de=k.floor(k.random()*k.pow(10,12));b.t=(new q).getTime();b.i="MOAT_FEATHER_DEBUG1";b.gw="mansuetodfp4895838934";b.cm="1";b.f=a.b.b?0:1;b.bq=0;b.ar="e27dbc83ae5-clean";b.iw="1347236";a.b.c&&(b.dMoatOQs=a.b.c);a.c.a(b);window[a.c.b()]=n}};a.c.g=function(a){n&&n.sp(a)};a.c.a=function(a){n&&n.__d(a)};a.c.b=function(){return n&&n.an()};a.c.h=function(){return!!n&&n.FPAA()};a.c.i=function(b){var c={};c.fq=b.HEADER_TRACKING?"1":"0";c.sy=b.HEADER_TRACKING?"1":"0";b.NAMED_IFRAME?(c.gh=1,c.wb=2):(c.gh=0,
c.wb=0);a.c.a(c)};a.c.j=function(a){try{var c=a.className,e=a.getAttribute("src");c.split("\n").join(" ");if(-1!==c.indexOf("moatfooter"))return!1;var l=e.split("?"),f=e.split("#");a=!1;1<l.length&&1<f.length&&l[1].length<f[1].length&&(a=!0);if(1==l.length||a)l=f;if(1<l.length){for(var h=l[1],g,f=h,l={},f=f.replace(/&amp;/g,"&").replace(/(^\s+|\s+$)/g,""),u=f.split("&"),f=0;f<u.length;f++){var m=u[f].split("=");if("string"===typeof m[1]){m[0]&&m[0].match("moatClient")&&(l["rawM"+m[0].slice(1)]=m[1]);
a=m;var r,d=m[1],c=d;try{for(e=0;100>e&&(d=decodeURIComponent(d),c!=d)&&!d.match(/^http(s)?\:/);e++)c=d}catch(k){}r=d.replace(/(^\s+|\s+$)/g,"");a[1]=r}else m[1]="";l[m[0]]=m[1]}if(u=l){for(var p in u)u.hasOwnProperty(p)&&p&&p.match("moatClientLevel")&&"string"===typeof u[p]&&(u[p]=u[p].replace(/\:/g,"_").replace(/%3A/gi,"_"));l=u}else l=void 0;g=l;g._originalQueryString=h;return g}return!1}catch(k){return!1}};a.c.c=function(a){return a&&a.document&&a.location&&a.alert&&a.setInterval};a.c.d=function(a){return(a=
v.toString.call(a))&&("[object Array]"===a||"[object Array Iterator]"===a)};a.c.k=g;a.c.forEach=d;a.c.l=function(a){return a.parentNode||a.parentElement||!1};a.c.hasChildNodes=function(a){return a&&a.childNodes&&0<a.childNodes.length};a.c.m=function(a,c){return!c(a.parent)&&!c(a.top)};a.c.n=function(){return{HEADER_TRACKING:!1,NAMED_IFRAME:!1}};a.c.o=function(){};a.c.p=function(a,c){var e=a.parentNode&&a.parentNode.getElementsByTagName("script"),g=!1;1>!e.length&&1>!c.length&&d(e,function(a){for(var b=
0;b<c.length;++b)if(-1<a.src.indexOf(c[b]+"/moatad.js"))return g=!0,!1});return g}})();(function(){function e(b,c,e){if(!b)return[];var f="boolean"===typeof e?e:!1,g=[b],d=!1;a.c.forEach("number"===typeof c?c:50,function(){if((d=a.c.l(b))&&1==d.nodeType)b=d,g.push(b);else if(f&&d&&9==d.nodeType)if((d=a.d.a(b))&&1==d.nodeType)b=d,g.push(b);else return!1;else return!1});return g}function g(b){if(!b)return!1;if("OBJECT"!==b.nodeName&&"EMBED"!==b.nodeName)return b;b=e(b);var c=!1;a.c.forEach(b,function(a){if(a&&
"OBJECT"!==a.nodeName&&"EMBED"!==a.nodeName)return c=a,!1});return c}function d(b,c){if(!b||!c)return!1;var e=g(c);if(!e)return!1;if(a.c.hasChildNodes(e)){var f=e.childNodes[k.max(0,e.childNodes.length-1)]||null;e.insertBefore(b,f)}else e.appendChild(b);return e}function n(a,b,c){"function"===typeof a.addEventListener?a.addEventListener(b,c):"function"===typeof a.attachEvent&&a.attachEvent("on"+b,c)}function v(b){if(l){h&&"function"===typeof window.clearTimeout&&window.clearTimeout(h);h=null;try{window.document.documentElement.removeChild(f),
f=null}catch(c){}a.c.i(b);a.c.g({LOAD:!0})}}function b(){if(q)return!1;q=!0;t()}function c(b){var c=b.indexOf("#"),e=b.indexOf("?");-1===c&&-1===e?b+="#":"&"!==b[b.length-1]&&(b+="&");c="fMoatCb="+a.c.b();return b+c}function t(){if(l){var b=document.createElement("script"),e=w.src.replace("moatad.js","moatcore.js");b.src=c(e);b.onerror=a.c.e(function(a){throw Error("Error loading fallback tag");});a.c.l(w).appendChild(b);return b}}var l={pcode:"mansuetoprebidheader15141606144"},f,h,q;a.e=a.e||{};
a.e.a=v;a.e.b=b;a.e.c=function(b,c){if(l){var e=!1,f;f=a.c.e(function(d){if(!e&&d&&d.data&&"string"===typeof d.data&&(d=d.data.match(/MSFAPI#1.2#[0-9]+#header_detector#[0-9]+#(.+)/i))){var g=a.c.n();"1"===d[1]?(g.HEADER_TRACKING=!0,v(g),b&&b()):(v(g),c&&c());e=!0;d=window;"function"===typeof d.removeEventListener?d.removeEventListener("message",f):"function"===typeof d.detachEvent&&d.detachEvent("onmessage",f)}});n(window,"message",f)}};a.e.d=t;a.e.e=function(){return q};a.e.f=function(a){q=a};a.e.g=
function(){if(l){var c=function(){if(null===h)return!1;var c=a.c.n();v(c);b()},e=!1;try{var g=document.createElement("iframe");g.src="https://z.moatads.com/hd09824092/iframe.html#slot=1";g.style.display="none";g.style.width="0px";g.style.height="0px";g.width="0";g.height="0";e=d(g,window.document.documentElement);f=g;if("function"===typeof window.setTimeout){var k=a.c.e(c);h=window.setTimeout(k,2E3)}}catch(p){}e||c()}}})();(function(){a.d=a.d||{};a.d.b=function(a,d){};a.d.c=function(a){try{var d=
typeof a.location.toString;if("undefined"===d||"unknown"===d)return!0;var k=typeof a.document;if("undefined"===k||"unknown"===k)return!0;var n=a.innerWidth||a.document.documentElement.clientWidth||a.document.body.clientWidth||0;return"number"!==typeof(a.screenX||a.screenLeft||0)||"number"!==typeof n?!0:!1}catch(q){return!0}}})();var w=function(a){if(!a)return null;var d=a.currentScript;if(y(d,"moatad.js","moatFoundMANSUETODFPCW3"))return d;a=a.getElementsByTagName("script");for(d=a.length-1;-1<
d;d--)if(y(a[d],"moatad.js","moatFoundMANSUETODFPCW3"))return a[d];return null}(document);if(w){var d=a.c.j(w);a.b={};a.b.a={moatClientLevel1:"MANSUETODFPCW3",moatClientLevel2:d&&(d.moatClientSlicer1||"-"),moatClientLevel3:d&&(d.moatClientSlicer2||"-"),moatClientLevel4:d&&(d.moatClientSlicer3||"-")};a.b.d="MANSUETODFPCW3";a.b.e=d;a.b.c=d&&d._originalQueryString;a.b.b=C(window,a.d.c);d=a.c.n();a.c.f();if(a.b.b){var B=window.top["__moatSlotTagLoaded"+t.pcode];"function"===typeof B?(d.HEADER_TRACKING=
!0,a.e.a(d),t.sli="MANSUETODFPCW3",B(w,t)):(a.e.a(d),a.e.b())}else D()?(d.HEADER_TRACKING=!0,d.NAMED_IFRAME=!0,a.e.a(d),z()):(a.e.c(z,a.e.b),a.e.g())}})(Date,Math)}catch(q){var GLOBAL_VAR=this,ct=(new Date).getTime();GLOBAL_VAR["Moat#ETS"]||(GLOBAL_VAR["Moat#ETS"]=ct);GLOBAL_VAR["Moat#EMC"]||(GLOBAL_VAR["Moat#EMC"]=0);var et=ct-GLOBAL_VAR["Moat#ETS"],hourElapsed=36E5<=et,msg=q.name+" in closure (global): "+q.message+", stack="+q.stack;if(!hourElapsed&&10>GLOBAL_VAR["Moat#EMC"]){GLOBAL_VAR["Moat#EMC"]++;
try{var pixelDomain="px.moatads.com",isDomless="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf),documentReferrer=isDomless?"":document.referrer,isBeta=!1,viewHash="undefined"===typeof AD_VIEW_HASH?isBeta?"MANSUETODFPCW3_BETA":"MANSUETODFPCW3":AD_VIEW_HASH,tagType="undefined"!==typeof Moat&&Moat.a&&Moat.a.a?Moat.a.a:"",pxSrc="https://"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(viewHash)+"&k="+escape(msg)+"&ar="+escape("e27dbc83ae5-clean")+
"&iw="+escape("1347236")+"&bq="+escape(tagType)+"&j="+escape(documentReferrer)+"&cs="+(new Date).getTime();if(isDomless)omidNative.sendUrl(pxSrc);else{var moat_px=new Image(1,1);moat_px.src=pxSrc}}catch(k){}}else if(hourElapsed){GLOBAL_VAR["Moat#EMC"]=1;GLOBAL_VAR["Moat#ETS"]=ct;try{pixelDomain="px.moatads.com",documentReferrer=(isDomless="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf))?"":document.referrer,isBeta=!1,viewHash="undefined"===typeof AD_VIEW_HASH?
isBeta?"MANSUETODFPCW3_BETA":"MANSUETODFPCW3":AD_VIEW_HASH,tagType="undefined"!==typeof Moat&&Moat.a&&Moat.a.a?Moat.a.a:"",pxSrc="https://"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(viewHash)+"&k="+escape(msg)+"&ar="+escape("e27dbc83ae5-clean")+"&iw="+escape("1347236")+"&bq="+escape(tagType)+"&j="+escape(documentReferrer)+"&cs="+(new Date).getTime(),isDomless?omidNative.sendUrl(pxSrc):(moat_px=new Image(1,1),moat_px.src=pxSrc)}catch(k){}}};
